apiVersion: v1
kind: Secret
metadata:
  name: secret-code
  namespace: secure
type: Opaque
data:
  code: dHJ1c3RubzEK
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-keeper
  namespace: secure
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo $SECRET_STUFF; sleep 3600']
    env:
    - name: SECRET_STUFF
      valueFrom:
        secretKeyRef:
          name: secret-code
          key: code