apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
      env: main
  template:
    metadata:
      labels:
        app: auth
        env: main
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: labels
          mountPath: /usr/share/nginx/html
      volumes:
      - name: labels
        downwardAPI:
          items:
          - path: index.html
            fieldRef:
              fieldPath: metadata.labels