apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-canary
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      env: canary
  template:
    metadata:
      labels:
        app: auth
        env: canary
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: labels
          mountPath: /usr/share/nginx/html
      volumes:
      - name: labels
        downwardAPI:
          items:
          - path: index.html
            fieldRef:
              fieldPath: metadata.labels