apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
          - name: print
            image: busybox:stable
            command: ["echo", "This is a text!"]
          restartPolicy: Never
