apiVersion: apps/v1
kind: Deployment
metadata:
	name: rolling-deployment
spec:
	progressDeadlineSeconds: 600
	replicas: 5
	revisionHistoryLimit: 10
	strategy:
		rollingUpdate:
			maxSurge: 10%
			maxUnavailable: 2
		type: RollingUpdate
	selector:
		matchLabels:
			app: rolling
	template:
		metadata:
		labels:
			app: rolling
		spec:
			containers:
			-	name: nginx
				image: nginx:1.14.2
				ports:
				-	containerPort: 80
							