apiVersion: v1
kind: ConfigMap
metadata:
  name: kenobi
  namespace: yoda
data:
  planet: hoth
---
apiVersion: v1
kind: Pod
metadata:
  name: chewie
  namespace: yoda
spec:
  containers:
  - name: nginx
    image: nginx:stable
    volumeMounts:
    - name: foo
      mountPath: "/etc/starwars"
  volumes:
  - name: foo
    configMap:
      name: kenobi