apiVersion: batch/v1
kind: CronJob
metadata:
  name: pwd-runner
  namespace: one
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
          - name: somename
            image: busybox:stable
            command: ['sh', '-c', 'pwd']
          restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: two
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dep
  template:
    metadata:
      labels:
        app: nginx-dep
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 8081
        env:
        - name: NGINX_PORT
          value: "8081"