apiVersion: v1
kind: Pod
metadata:
  name: apple
  namespace: dev
spec:
  containers:
  - name: lab06
    image: nginx:stable
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-code
  namespace: secure
type: Opaque
data:
  code: dHJ1c3RubzE=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-keeper
  namespace: secure
spec:
  containers:
  - name: somename
    image: busybox:stable
    command: ['sh', '-c', 'echo $SECRET_STUFF;', 'sleep 3600']
    env:
      - name: SECRET_STUFF
        valueFrom:
          secretKeyRef:
            name: secret-code
            key: code